### ISSUE TITLE
VS with many stream sources

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#10]
Is it a feature to have many stream sources for one virtual sensor or should it be only one source per sensor ?

If it is normal, should we have the possibility to select each field of each source in a VS ? (what about VS that are the same ? (make no sense to have twice a GPS sensor because they will have exactly the same data, right ?)

**Comment by ebiiii** [comment]
Sensor Wrappers are singletons (almost...). So it means that all virtual sensor that will listen to the GPS will receive the same data at the same rate. 
Virtual Sensors can be instantiated many times, they are uniquely identifiable by their names.
To make a "many-to-many" relationship between those (a wrapper can output to several VS and a VS can have several wrappers as input), we use FIFO queues (StreamSource). 
In addition to link a wrapper to a VS, they also define a sliding window processing and aggregation.
When receiving the stream-element the VS knows also where they are from and can apply different processing according to their sources. One "problem" is that the user can connect any wrapper and currently the VS are assuming that they have the correct one connected, thus crashing if they receive the wrong fields.
Wrappers (or sources) are not expected to change the stream-element structure and select sub-sets of fields (unlike the server version of GSN).
