### ISSUE TITLE
Remodel the DB

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#12]
Remove some columns from the DB and think about avec a DB with a key-value schema where values are JSON strings

**Comment by AblionGE** [comment]
Removed all columns about NotifyVS.

**Comment by AblionGE** [comment]
Still need to think about storing data with JSON values

**Comment by ebiiii** [comment]
The KV storage is interesting when you don't need the SQL queries and advantages, but need more flexibility, like for storing the parameters and settings. So for the other tables, like vs_*, I would keep them in table format. Which tables were you thinking to change?

**Comment by AblionGE** [comment]
Should be OK like it is now
