### ISSUE TITLE
Recode Android Activity

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#4]
- [x] AndroidActivityRecognitionWrapper
  - [x] disconnect for GoogleAPI when not running
- [x] notificationvirtualsensor

**Comment by AblionGE** [comment]
@ebiiii What do you mean by that exactly ?

**Comment by ebiiii** [comment]
This is also important, especially as the dependencies of the activityrecognitionwrapper may have changed (not sure if it is still part of the goolge play lib...). Also this will clean a bit the way virtual sensors are stored, by removing fields specific to the notifications.

**Comment by AblionGE** [comment]
Really nice example for ActivityRecognition : http://tutsberry.com/activity-recognition-implementation-on-android/

**Comment by AblionGE** [comment]
`AndroidActivityRecognitionWrapper` is working now. Need to be tested IRL (not only in front of the computer :) )

**Comment by AblionGE** [comment]
moved `addViewNotifyConfig()` from `ActivityVSConfig` to `NotificationVirtualSensor`

Still need to adapt `saveVS()`, values are not up to date for NotificationVS. Causes #9

**Comment by AblionGE** [comment]
@ebiiii we have to discuss if we can merge in some way `SettingPanel` and what is given by the new function `getRowParameters()`

**Comment by ebiiii** [comment]
you don't need to add new methods, you can just keep the getParameters() and the original SettingPanel. 
(indeed currently it only supports textfields and we may loose the spinners.)

**Comment by AblionGE** [comment]
`SettingPanel` recoded. Will continue in  more specific issues (#14 and #13 )
