### ISSUE TITLE
Publish Service for auto/opportunistic

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/gsn#5]
Publish Service is at the moment only manual. It could be improved in two manners :
- automatically - every x unit of time
- opportunistically - when wifi for example

**Comment by ebiiii** [comment]
This can be inspired by the way the wrappers perform periodic tasks. The only difference between the two strategies is that the opportunistic one will not use cellular connections and will not initiate a wifi connection if the wifi is not already connected to an access point. This is important to have at least one of those options available.

**Comment by AblionGE** [comment]
Both of these services are almost done. For the opportunistic one, I will keep exactly the same code as the periodic one except that it only sends data when wifi is connected.

**Comment by AblionGE** [comment]
To implement these publishers, I used the same mechanism as for the wrapper (`IntentService`).
